FROM archlinux:base-devel

RUN pacman -Syu --noconfirm && \
    pacman -S --needed --noconfirm sudo git meson gobject-introspection glib2-devel wayland-protocols sysprof python-docutils

RUN useradd -m -u 1000 builduser && \
    echo "builduser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER builduser
WORKDIR /workspace

CMD ["makepkg", "-s", "-f", "--noconfirm", "--clean"]
